export class Cocktail {
    public constructor(
        public idDrink: string,
        public strDrinkThumb: string,
        public strGlass: string,
        public strDrink: string,
        public strIngredient1: string | null,
        public strIngredient2: string | null,
        public strIngredient3: string | null,
        public strIngredient4: string | null,
        public strIngredient5: string | null,
        public strIngredient6: string | null,
        public strIngredient7: string | null,
        public strIngredient8: string | null,
        public strIngredient9: string | null,
        public strIngredient10: string | null,
        public strIngredient11: string | null,
        public strIngredient12: string | null,
        public strIngredient13: string | null,
        public strIngredient14: string | null,
        public strIngredient15: string | null,
        public strInstructions: string,
        public strMeasure1: string,
        public strMeasure2: string,
        public strMeasure3: string,
        public strMeasure4: string,
        public strMeasure5: string,
        public strMeasure6: string,
        public strMeasure7: string,
        public strMeasure8: string,
        public strMeasure9: string,
        public strMeasure10: string,
        public strMeasure11: string,
        public strMeasure12: string,
        public strMeasure13: string,
        public strMeasure14: string,
        public strMeasure15: string,
    ){};
}